package com.itangcent.easyapi.exporter.formatter

import com.itangcent.easyapi.exporter.model.ApiEndpoint
import com.itangcent.easyapi.exporter.model.HttpMethod
import com.itangcent.easyapi.exporter.model.ParameterBinding

/**
 * Formatter for generating IntelliJ HTTP Client file format.
 * 
 * This formatter generates .http files compatible with IntelliJ IDEA's
 * built-in HTTP Client. The format supports:
 * - HTTP method and URL specification
 * - Headers
 * - Request body (JSON and form data)
 * - Query parameters
 * 
 * Output can be directly used in IntelliJ for API testing.
 */
class HttpClientFileFormatter {

    /**
     * Formats a single API endpoint as an HTTP Client request.
     * 
     * @param endpoint The API endpoint to format
     * @param host Optional host URL to prepend to the path
     * @return A string in HTTP Client format
     */
    fun format(endpoint: ApiEndpoint, host: String = ""): String {
        val sb = StringBuilder()
        
        sb.append("### ${endpoint.name ?: endpoint.path}\n")
        if (endpoint.description != null) {
            sb.append("# ${endpoint.description}\n")
        }
        sb.append("\n")

        val queryParams = endpoint.parameters
            .filter { it.binding == ParameterBinding.Query }
            .mapNotNull { param ->
                val value = param.defaultValue ?: param.example ?: return@mapNotNull null
                "${param.name}=$value"
            }
            .joinToString("&")

        val url = buildString {
            if (host.isNotBlank()) {
                append(host.trimEnd('/'))
            }
            append(endpoint.path)
            if (queryParams.isNotEmpty()) {
                append("?$queryParams")
            }
        }

        sb.append("${endpoint.method.name} $url\n")

        for (header in endpoint.headers) {
            val value = header.value ?: continue
            sb.append("${header.name}: $value\n")
        }

        val bodyParams = endpoint.parameters
            .filter { it.binding == ParameterBinding.Body }
        
        if (bodyParams.isNotEmpty() && endpoint.method in listOf(HttpMethod.POST, HttpMethod.PUT, HttpMethod.PATCH)) {
            sb.append("\n")
            sb.append("{\n")
            bodyParams.forEachIndexed { index, param ->
                val value = param.example ?: param.defaultValue ?: ""
                val comma = if (index < bodyParams.size - 1) "," else ""
                sb.append("  \"${param.name}\": \"$value\"$comma\n")
            }
            sb.append("}\n")
        }

        sb.append("\n")
        
        return sb.toString()
    }

    /**
     * Formats multiple API endpoints as an HTTP Client file.
     * Includes a header comment with file name and endpoint count.
     * 
     * @param endpoints The list of API endpoints to format
     * @param host Optional host URL to prepend to paths
     * @param fileName The name for the file header
     * @return A complete HTTP Client file content
     */
    fun formatAll(endpoints: List<ApiEndpoint>, host: String = "", fileName: String = "api"): String {
        val sb = StringBuilder()
        sb.append("### $fileName\n")
        sb.append("### Generated by EasyAPI\n")
        sb.append("### Total: ${endpoints.size} endpoints\n\n")
        
        for (endpoint in endpoints) {
            sb.append(format(endpoint, host))
            sb.append("\n")
        }
        
        return sb.toString()
    }
}
