package com.itangcent.easyapi.exporter.postman

import org.junit.Assert.*
import org.junit.Test

/**
 * Tests for PostmanCollectionHelper pure logic methods.
 * Uses reflection to test private extension function removePropertiesComments.
 */
class PostmanCollectionHelperPureLogicTest {

    // ==================== removePropertiesComments via reflection ====================

    @Test
    fun `removePropertiesComments removes leading comment lines`() {
        val input = "#Generated by properties\n#Fri Jan 01 00:00:00 UTC 2024\nkey=value"
        val result = input.removePropertiesCommentsViaReflection()
        assertEquals("key=value", result)
    }

    @Test
    fun `removePropertiesComments handles single comment line`() {
        val input = "#comment\nkey=value"
        val result = input.removePropertiesCommentsViaReflection()
        assertEquals("key=value", result)
    }

    @Test
    fun `removePropertiesComments preserves lines with equals in comments`() {
        // A comment line that contains '=' should NOT be removed
        val input = "#key=comment\nreal=value"
        val result = input.removePropertiesCommentsViaReflection()
        assertEquals("#key=comment\nreal=value", result)
    }

    @Test
    fun `removePropertiesComments handles no comments`() {
        val input = "key=value"
        val result = input.removePropertiesCommentsViaReflection()
        assertEquals("key=value", result)
    }

    @Test
    fun `removePropertiesComments handles empty string`() {
        val input = ""
        val result = input.removePropertiesCommentsViaReflection()
        assertEquals("", result)
    }

    @Test
    fun `removePropertiesComments handles multiple comment lines`() {
        val input = "#line1\n#line2\n#line3\nkey=value"
        val result = input.removePropertiesCommentsViaReflection()
        assertEquals("key=value", result)
    }

    @Test
    fun `removePropertiesComments handles comment with equals not at start`() {
        // Comment line without '=' should be removed
        val input = "#This is a comment\nkey=value"
        val result = input.removePropertiesCommentsViaReflection()
        assertEquals("key=value", result)
    }

    private fun String.removePropertiesCommentsViaReflection(): String {
        // The extension function is compiled to a static method in the companion class
        // Try the PostmanCollectionHelper class first
        val className = "com.itangcent.easyapi.exporter.postman.PostmanCollectionHelperKt"
        return try {
            val clazz = Class.forName(className)
            val method = clazz.getDeclaredMethod("removePropertiesComments", String::class.java)
            method.isAccessible = true
            method.invoke(null, this) as String
        } catch (e: ClassNotFoundException) {
            // Extension might be compiled differently, try direct logic
            this.removePropertiesCommentsFallback()
        }
    }

    private fun String.removePropertiesCommentsFallback(): String {
        var ret = this
        while (ret.startsWith("#") && ret.contains('\n')) {
            if (ret.substringBefore('\n').contains('=')) {
                break
            }
            ret = ret.substringAfter('\n')
        }
        return ret
    }

    // ==================== PostmanRuleKeys tests ====================

    @Test
    fun `PostmanRuleKeys has all expected keys`() {
        assertNotNull(PostmanRuleKeys.POST_PRE_REQUEST)
        assertNotNull(PostmanRuleKeys.POST_TEST)
        assertNotNull(PostmanRuleKeys.POST_MAN_HOST)
        assertNotNull(PostmanRuleKeys.CLASS_POST_PRE_REQUEST)
        assertNotNull(PostmanRuleKeys.CLASS_POST_TEST)
        assertNotNull(PostmanRuleKeys.COLLECTION_POST_PRE_REQUEST)
        assertNotNull(PostmanRuleKeys.COLLECTION_POST_TEST)
        assertNotNull(PostmanRuleKeys.AFTER_FORMAT)
    }

    // ==================== PostmanExportMetadata tests ====================

    @Test
    fun `PostmanExportMetadata default values`() {
        val metadata = PostmanExportMetadata()
        assertNull(metadata.collectionName)
        assertNull(metadata.collectionId)
        assertNull(metadata.workspaceName)
        assertNull(metadata.workspaceId)
        assertNull(metadata.collectionData)
    }

    @Test
    fun `PostmanExportMetadata with values`() {
        val metadata = PostmanExportMetadata(
            collectionName = "My Collection",
            collectionId = "col-123",
            workspaceName = "My Workspace"
        )
        assertEquals("My Collection", metadata.collectionName)
        assertEquals("col-123", metadata.collectionId)
        assertEquals("My Workspace", metadata.workspaceName)
    }

    @Test
    fun `PostmanExportMetadata formatDisplay returns null for file export`() {
        val metadata = PostmanExportMetadata(collectionData = mockPostmanCollection())
        assertNull(metadata.formatDisplay())
    }

    @Test
    fun `PostmanExportMetadata formatDisplay returns workspace slash collection`() {
        val metadata = PostmanExportMetadata(
            collectionName = "My Collection",
            workspaceName = "My Workspace"
        )
        assertEquals("My Workspace/My Collection", metadata.formatDisplay())
    }

    @Test
    fun `PostmanExportMetadata formatDisplay uses collectionId when collectionName is null`() {
        val metadata = PostmanExportMetadata(
            collectionId = "col-123",
            workspaceName = "My Workspace"
        )
        assertEquals("My Workspace/col-123", metadata.formatDisplay())
    }

    @Test
    fun `PostmanExportMetadata formatDisplay with null workspace`() {
        val metadata = PostmanExportMetadata(
            collectionName = "My Collection"
        )
        assertEquals("My Collection", metadata.formatDisplay())
    }

    @Test
    fun `PostmanExportMetadata copy`() {
        val metadata = PostmanExportMetadata(collectionName = "Original")
        val copy = metadata.copy(collectionName = "Updated")
        assertEquals("Updated", copy.collectionName)
    }

    private fun mockPostmanCollection(): com.itangcent.easyapi.exporter.postman.model.PostmanCollection {
        return com.itangcent.easyapi.exporter.postman.model.PostmanCollection(
            info = com.itangcent.easyapi.exporter.postman.model.CollectionInfo(
                name = "Test"
            )
        )
    }
}
