package com.itangcent.easyapi.exporter.postman

import org.junit.Assert.*
import org.junit.Test

/**
 * Tests for PostmanCollectionHelper utility functions
 * that don't require a Project instance.
 */
class PostmanCollectionHelperUtilsTest {

    // --- removePropertiesComments logic (replicated for testing) ---

    private fun String.removePropertiesComments(): String {
        var ret = this
        while (ret.startsWith("#") && ret.contains('\n')) {
            if (ret.substringBefore('\n').contains('=')) {
                break
            }
            ret = ret.substringAfter('\n')
        }
        return ret
    }

    @Test
    fun testRemovePropertiesCommentsWithComment() {
        val input = "#Generated by Properties\nkey=value"
        val result = input.removePropertiesComments()
        assertEquals("key=value", result)
    }

    @Test
    fun testRemovePropertiesCommentsWithMultipleComments() {
        val input = "#Comment 1\n#Comment 2\nkey=value"
        val result = input.removePropertiesComments()
        assertEquals("key=value", result)
    }

    @Test
    fun testRemovePropertiesCommentsNoComment() {
        val input = "key=value"
        val result = input.removePropertiesComments()
        assertEquals("key=value", result)
    }

    @Test
    fun testRemovePropertiesCommentsCommentWithEquals() {
        val input = "#timestamp=12345\nkey=value"
        val result = input.removePropertiesComments()
        // Comment line contains '=', so it should stop removing
        assertEquals("#timestamp=12345\nkey=value", result)
    }

    @Test
    fun testRemovePropertiesCommentsEmptyString() {
        val input = ""
        val result = input.removePropertiesComments()
        assertEquals("", result)
    }

    @Test
    fun testRemovePropertiesCommentsOnlyComment() {
        val input = "#Just a comment"
        val result = input.removePropertiesComments()
        assertEquals("#Just a comment", result)
    }
}
