package com.itangcent.common.model

/**
 * MethodDoc represents a document generated by a Java method that may not include any HTTP request.
 * In general it could be an RPC interface.
 */
class MethodDoc : Doc() {

    var params: MutableList<Param>? = null

    var ret: Any? = null

    var retDesc: String? = null
}