name: PR Package and Comment

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  package-and-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Check for issue number
        id: check_issue
        shell: bash
        run: |
          # Store PR body in a file to avoid shell interpretation issues
          echo '${{ github.event.pull_request.body }}' > pr_body.txt
          
          # Check for issue reference pattern
          if grep -q "#[0-9]\\+" pr_body.txt; then
            ISSUE_NUM=$(grep -o "#[0-9]\\+" pr_body.txt | head -n 1 | tr -d '#')
            echo "issue_number=${ISSUE_NUM}" >> $GITHUB_OUTPUT
            echo "has_issue=true" >> $GITHUB_OUTPUT
          else
            echo "has_issue=false" >> $GITHUB_OUTPUT
          fi

      - name: Package plugin
        run: ./plugin-script/package_plugin.sh

      - name: Get plugin filename
        id: get_filename
        run: |
          FILENAME=$(ls plugin/easy-yapi-*.zip | xargs basename)
          echo "plugin_filename=${FILENAME}" >> $GITHUB_OUTPUT

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_filename.outputs.plugin_filename }}
          path: plugin/easy-yapi-*.zip
          if-no-files-found: error

      - name: Comment on target issue
        if: steps.check_issue.outputs.has_issue == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const issueNumber = '${{ steps.check_issue.outputs.issue_number }}';
            const pluginFilename = '${{ steps.get_filename.outputs.plugin_filename }}';
            const workflowRunUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `A PR (#${pr.number}) has been opened to fix this issue. You can download the packaged plugin \`${pluginFilename}\` from the [GitHub Actions workflow run](${workflowRunUrl}) by clicking on the "Artifacts" dropdown.`
            });

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const pluginFilename = '${{ steps.get_filename.outputs.plugin_filename }}';
            const workflowRunUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `📦 Plugin has been packaged for this PR. You can download \`${pluginFilename}\` from the [GitHub Actions workflow run](${workflowRunUrl}) by clicking on the "Artifacts" dropdown.`
            }); 