name: 'Close stale issues'
on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 20
          days-before-close: 5
          exempt-issue-labels: 'release,wait-for-release'
          stale-issue-label: 'wontfix'
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          close-issue-message: ''  # No close message as per your config
          # Using the same settings for PRs as issues
          days-before-pr-stale: 20
          days-before-pr-close: 5
          exempt-pr-labels: 'release,wait-for-release'
          stale-pr-label: 'wontfix'
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          close-pr-message: '' 